global_frame: alpha_rise/odom
robot_base_frame: alpha_rise/base_link
transform_tolerance: 2.0
update_frequency: 10.0
static_map: false
obstacle_range: 10.0
raytrace_range: 30.0
# footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]
# inflation_radius: 0.55

plugins:
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}

obstacles:
  observation_sources: laser_scan_sensor
  # laser_scan_sensor: {
  #   sensor_frame: alpha_rise/ping360_link, 
  #   data_type: LaserScan, 
  #   topic: /alpha_rise/scan, 
  #   observation_persistance: 60,
  #   marking: true,
  #   clearing: true
  #   }

  laser_scan_sensor: {
    sensor_frame: alpha_rise/ping360_link,
    data_type: PointCloud2,
    topic: /alpha_rise/pointcloud/filtered,
    observation_persistance: 20,
    marking: true,
    clearing: false,
    max_obstacle_height: 5,
    min_obstacle_height: -10
  }