global_frame: alpha_rise/odom
robot_base_frame: alpha_rise/base_link
transform_tolerance: 2.0
update_frequency: 10.0
static_map: false
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]
inflation_radius: 0.55

plugins:
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}

obstacles:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {
    sensor_frame: alpha_rise/ping360_link, 
    data_type: LaserScan, 
    topic: /alpha_rise/scan, 
    marking: true,
    clearing: true}