/alpha_rise/costmap:
    ros__parameters:
      global_frame: alpha_rise/odom
      robot_base_frame: alpha_rise/base_link
      transform_tolerance: 2.0
      update_frequency: 10.0
      publish_frequency: 10.0
      static_map: false
      rolling_window: true
      always_send_full_costmap: true
      #The dimensions of the costmap(cells) is width(m) * 1/resolution(m/cmminell) x height(m) * 1/resolution(m/cell)  
      width: 100
      height: 100 #100x100 for sf #20x20 for real # 2*number of bins or 2*range
      resolution: 1.0 #0.5 #meters per cell #0.05 for real. #0.5 for sf

      plugins: ["obstacle_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        # Add your sources here
        observation_sources: pointcloud_sf

        #Stonefish
        pointcloud_sf:
          sensor_frame: alpha_rise/ping360_link_sf
          data_type: "PointCloud2"
          topic: /alpha_rise/stonefish/msis/data/pointcloud/filtered
          #How long to keep each sensor reading in seconds. A value of 0.0 will only keep the most recent reading.
          observation_persistence: 0.0
          #Whether or not this observation should be used to mark obstacles.
          marking: true
          #Whether or not this observation should be used to clear out freespace
          clearing: true
          #The maximum height in meters of a sensor reading considered valid. 
          max_obstacle_height: 5.0
          #The minimum height in meters of a sensor reading considered valid
          min_obstacle_height: -20.0
          raytrace_max_range: 50.0
          raytrace_min_range: 0.0
          obstacle_max_range: 50.0
          obstacle_min_range: 0.0