pcl_filter:
  stonefish: true
  sf_sub_topic: '/alpha_rise/msis/stonefish/data/pointcloud'
  sf_radial_filter_param: 5
  sf_std_dev_multiplier: 2.5

  sub_topic: '/alpha_rise/msis/pointcloud'
  radial_filter_param: 120
  std_dev_multiplier: 2.25