local_costmap:
  global_frame: alpha_rise/odom
  robot_base_frame: alpha_rise/base_link
  update_frequency: 10.0
  publish_frequency: 2.0
  static_map: true
  static_layer:
    map_topic: /map
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  plugins:
#   - name: sonar_layer
#     type: "sonar_layer::SonarLayer"
   - name: obstacle_layer
     type: "costmap_2d::ObstacleLayer"