/alpha_rise/loop_checker:
  ros__parameters:
    moment_comparison_threshold: 0.3 #lower is more similiar
    cosine_similarity_threshold: 0.9 #higher is more similiar
    msis_scan_time: 26.0 #time taken for a new scan image