/**:
  ros__parameters:
    # shared
    vertical_fov_deg: 25.0
    resolution: 1.0
    marker_topic: /alpha_rise/msis/geometry
    
    # msis_voxel_node
    range_max: 50.0
    horizontal_fov_deg: 2.0
    frame_id: "alpha_rise/ping360_link"
    
    # msis_prob_clouds
    intensity_threshold: 20.0
    min_range: 5.0
    z_max: -1.0
    cloud_sub_topic: /alpha_rise/msis/pointcloud
    fan_pub_topic: /alpha_rise/msis/pointcloud/probability
    range_filter_pub_topic: /alpha_rise/msis/intensity_range/range_filter
