path_generator:
  odom_frame: "alpha_rise/odom"
  base_frame: "alpha_rise/base_link"
  costmap_topic: 'move_base/local_costmap/costmap'
  path_topic: 'path'
  debug: false

  canny_min_threshold: 200
  canny_max_threshold: 255

  #To change polynomial, find model_f function in path.py
  standoff_distance_meters: 20
  points_to_sample_from_curve: 20

  min_scan_angle: -90 #degrees
  max_scan_angle: 90
  distance_constraint: 15 #meters

waypoint_admin:
  update_waypoint_topic: "helm/path_3d/update_waypoints"
  odom_topic: "/alpha_rise/odometry/filtered/local"
  get_state_service: "/alpha_rise/helm/get_state"
  change_state_service: "/alpha_rise/helm/change_state"
  get_waypoint_service: "/alpha_rise/helm/path_3d/get_next_waypoints"

  check_state_update_rate: 1 #sec
  z_value: -5 #meters 