path_generator:
  odom_frame: "alpha_rise/odom"
  base_frame: "alpha_rise/base_link"
  costmap_topic: 'move_base/local_costmap/costmap'
  path_topic: 'path'
  debug: false

  canny_min_threshold: 200
  canny_max_threshold: 255

  #To change polynomial, find model_f function in path_utils.py
  standoff_distance_meters: 20
  points_to_sample_from_curve: 20

  min_scan_angle: -90 #degrees
  max_scan_angle: 90
  distance_constraint: 15 #meters

waypoint_admin:
  update_waypoint_topic: "helm/path_3d/update_waypoints"
  odom_topic: "/alpha_rise/odometry/filtered/local"
  get_state_service: "/alpha_rise/helm/get_state"
  change_state_service: "/alpha_rise/helm/change_state"
  get_waypoint_service: "/alpha_rise/helm/path_3d/get_next_waypoints"
  max_yaw_rate: 0.8 #rad/s #0.8rad is 45degree
  check_state_update_rate: 1 #sec
  search_mode_timer: 1200 #sec
  follow_mode_timer: 2000 #sec
  z_value: -5 #meters 
  search_mode_initial_radius: 10 #m
  exit_mode_distance: 30 #m